project_id = "ccsfhblxkmyqdqqcgitt"

[functions.create-daily-attendance]
verify_jwt = false

[functions.generate-daily-reports]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.auto-generate-stock-id]
verify_jwt = false

[functions.send-smart-notifications]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.send-suspension-notification]
verify_jwt = false

[functions.generate-sales-pdf]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false
