// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://ccsfhblxkmyqdqqcgitt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc2ZoYmx4a215cWRxcWNnaXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzAzMjAsImV4cCI6MjA3ODIwNjMyMH0.RaeiO3GheEdNZNT6iA_DfiIg5RvGh_HLrlr9YfNg6vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Global lock to prevent concurrent token refreshes (refresh-token storm prevention)
let isRefreshing = false;
let refreshPromise: Promise<any> | null = null;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    fetch: async (url: RequestInfo | URL, options?: RequestInit) => {
      const response = await fetch(url, options);
      
      // If we get a 429, wait and DON'T retry automatically - let the caller handle it
      if (response.status === 429) {
        console.warn('Rate limited (429) - backing off');
      }
      
      return response;
    },
  },
});

// Wrap refreshSession to deduplicate concurrent calls
const originalRefreshSession = supabase.auth.refreshSession.bind(supabase.auth);
supabase.auth.refreshSession = async (...args: any[]) => {
  if (isRefreshing && refreshPromise) {
    return refreshPromise;
  }
  isRefreshing = true;
  refreshPromise = originalRefreshSession(...args).finally(() => {
    isRefreshing = false;
    refreshPromise = null;
  });
  return refreshPromise;
};
